# EDA CDC Places Dataset  

## Introduction

The Centers for Disease Control and Prevention (CDC) provides a dataset called "Places" that contains information about various health-related metrics at the county and city level across the United States. This dataset includes information on health outcomes, health behaviors, clinical care, social and economic factors, and physical environment.

This exploratory data analysis (EDA) focuses on understanding the structure of the CDC Places dataset, to identify patterns, trends, and potential areas for further analysis that can support the master dataset join. Key objectives include validating primary keys, identifying data quality issues (such as missingness), and assessing the distribution of core health metrics.

**Validation Revield limitations with the curent CDC Places dataset and the project goals, and the need for additional data sources to enhance the analysis. Analysis determiend that this dataset can be archived**

## Import Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# Read The CSV file

In [14]:
base_path = Path.cwd().parents[1]  # Get the parent directory of the current working directory

data_path = base_path / "data" / "raw"/ "cdc_places_raw.csv"

df = pd.read_csv(data_path)

print(f"Data loaded successfully")

Data loaded successfully

# Exploratory Data Analysis (EDA)

In [3]:
df.head()

,year,stateabbr,statedesc,countyname,countyfips,locationname,datasource,category,measure,data_value_unit,...,low_confidence_limit,high_confidence_limit,totalpopulation,totalpop18plus,geolocation,locationid,categoryid,measureid,datavaluetypeid,short_question_text
0,2023,AL,Alabama,Autauga,1001,1001020100,BRFSS,Prevention,Current lack of health insurance among adults ...,%,...,7.4,12.3,1775,1370,POINT (-86.4915648 32.4819731),1001020100,PREVENT,ACCESS2,CrdPrv,Health Insurance
1,2023,AL,Alabama,Autauga,1001,1001020100,BRFSS,Health Outcomes,Arthritis among adults,%,...,27.2,34.0,1775,1370,POINT (-86.4915648 32.4819731),1001020100,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis
2,2023,AL,Alabama,Autauga,1001,1001020100,BRFSS,Health Risk Behaviors,Binge drinking among adults,%,...,12.1,17.7,1775,1370,POINT (-86.4915648 32.4819731),1001020100,RISKBEH,BINGE,CrdPrv,Binge Drinking
3,2023,AL,Alabama,Autauga,1001,1001020100,BRFSS,Health Outcomes,High blood pressure among adults,%,...,37.1,45.7,1775,1370,POINT (-86.4915648 32.4819731),1001020100,HLTHOUT,BPHIGH,CrdPrv,High Blood Pressure
4,2023,AL,Alabama,Autauga,1001,1001020100,BRFSS,Prevention,Taking medicine to control high blood pressure...,%,...,74.9,80.4,1775,1370,POINT (-86.4915648 32.4819731),1001020100,PREVENT,BPMED,CrdPrv,High Blood Pressure Medication

In [4]:
df.shape

(3047284, 24)

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
year,3047284.0,2.022863e+03,3.438658e-01,2.022000e+03,2.023000e+03,2.023000e+03,2.023000e+03,2.023000e+03
countyfips,3047284.0,2.710148e+04,1.593084e+04,1.001000e+03,1.210100e+04,2.616300e+04,3.909500e+04,5.604500e+04
locationname,3047284.0,2.710173e+10,1.593085e+10,1.001020e+09,1.210103e+10,2.616358e+10,3.909501e+10,5.604595e+10
data_value,3047284.0,2.601500e+01,2.337885e+01,3.000000e-01,9.000000e+00,1.690000e+01,3.460000e+01,9.820000e+01
data_value_footnote_symbol,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_value_footnote,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
low_confidence_limit,3047284.0,2.353609e+01,2.244689e+01,2.000000e-01,7.600000e+00,1.450000e+01,3.040000e+01,9.770000e+01
high_confidence_limit,3047284.0,2.857956e+01,2.424116e+01,3.000000e-01,1.040000e+01,1.950000e+01,3.890000e+01,9.860000e+01
totalpopulation,3047284.0,3.971712e+03,1.672655e+03,5.400000e+01,2.774000e+03,3.787000e+03,4.952000e+03,3.789200e+04
totalpop18plus,3047284.0,3.093981e+03,1.275032e+03,5.000000e+01,2.184000e+03,2.959000e+03,3.845000e+03,3.128000e+04
locationid,3047284.0,2.710173e+10,1.593085e+10,1.001020e+09,1.210103e+10,2.616358e+10,3.909501e+10,5.604595e+10

There appears to be two empty columens data_value_footnote_symbol and data_value_footnote. These columns should likely be dropped as they do not contain any useful information.

Population: totalpopulation and totalpop18plus have outliers. The 75th percentile is ~4,952, but the max is 37,892. This indicates some very large counties or high-population outliers. Range goes form 0.3 to 98.2 which is a massive spread of heath metrics. Ceate a histogram to see if there is a noral distribution or if the data is skewed.

countyfips and locationid are showing up with numerical statistics (mean, min, max).
Warning: Even though they are numbers, they are actually categorical identifiers. Do not use these in any mathematical calculations.

In [6]:
df.isnull().sum()

year                                0
stateabbr                           0
statedesc                           0
countyname                          0
countyfips                          0
locationname                        0
datasource                          0
category                            0
measure                             0
data_value_unit                     0
data_value_type                     0
data_value                          0
data_value_footnote_symbol    3047284
data_value_footnote           3047284
low_confidence_limit                0
high_confidence_limit               0
totalpopulation                     0
totalpop18plus                      0
geolocation                         0
locationid                          0
categoryid                          0
measureid                           0
datavaluetypeid                     0
short_question_text                 0
dtype: int64

In [7]:
df.dtypes

year                            int64
stateabbr                      object
statedesc                      object
countyname                     object
countyfips                      int64
locationname                    int64
datasource                     object
category                       object
measure                        object
data_value_unit                object
data_value_type                object
data_value                    float64
data_value_footnote_symbol    float64
data_value_footnote           float64
low_confidence_limit          float64
high_confidence_limit         float64
totalpopulation                 int64
totalpop18plus                  int64
geolocation                    object
locationid                      int64
categoryid                     object
measureid                      object
datavaluetypeid                object
short_question_text            object
dtype: object

Data is well structured with a few hidden traps. 

Identifiers countyfips, locationid, and year are treated as interges. Should convert to objects. 

Categories and objects category, measure, data_value_unit, and short_question_text are correctly identified as objects. These are primary grouping variables. 

The Missingness Confirmed: data_value_footnote_symbol and data_value_footnote are float64 but were empty in your previous summary. These are safe to drop or ignore.

Location/Geolocation: geolocation may be needed later for spatial mapping.

## Target Variable

The target variable for this project is derived from the Data_Value column within the CDC PLACES dataset. This column represents the estimated age-adjusted prevalence—the percentage of the adult population in a given geographic area that has been diagnosed with a specific health outcome. In our case, we are focusing on High blood pressure among adults.

It is important to note that these values are model-based estimates generated by the CDC using Behavioral Risk Factor Surveillance System (BRFSS) data and other census-level information. Because this data is available at multiple levels of granularity—including counties, census tracts, and places—it provides a powerful lens through which to examine health disparities. In this section, we will dive into these specific columns to better understand the distribution of our target variable across these geographic units and identify potential trends that will inform our modeling approach.

Data_Value_Type: May contain a mixture of "Crude" and "Age-Adjusted" values. Use "Crude" for the actual raw percentages. Use "Age-Adjusted" values for comparisons across different populations, as they account for differences in age distribution.

In [13]:
# Get a summary of how many rows each combinaiton occupies 
summary = df.groupby(['measure', 'data_value_type']).size().reset_index(name='Count')

print(summary)

                                              measure   data_value_type  Count
0         All teeth lost among adults aged >=65 years  Crude prevalence  83488
1                         Any disability among adults  Crude prevalence  78815
2                              Arthritis among adults  Crude prevalence  78815
3                         Binge drinking among adults  Crude prevalence  78815
4          Cancer (non-skin) or melanoma among adults  Crude prevalence  78815
5                  Cholesterol screening among adults  Crude prevalence  78815
6   Chronic obstructive pulmonary disease among ad...  Crude prevalence  78815
7                   Cognitive disability among adults  Crude prevalence  78815
8   Colorectal cancer screening among adults aged ...  Crude prevalence  83519
9                 Coronary heart disease among adults  Crude prevalence  78815
10                        Current asthma among adults  Crude prevalence  78815
11             Current cigarette smoking among adults  Crude prevalence  78815
12  Current lack of health insurance among adults ...  Crude prevalence  78815
13                            Depression among adults  Crude prevalence  78815
14                    Diagnosed diabetes among adults  Crude prevalence  78815
15  Fair or poor self-rated health status among ad...  Crude prevalence  78815
16  Food insecurity in the past 12 months among ad...  Crude prevalence  60419
17              Frequent mental distress among adults  Crude prevalence  78815
18            Frequent physical distress among adults  Crude prevalence  78815
19                    Hearing disability among adults  Crude prevalence  78815
20                   High blood pressure among adults  Crude prevalence  78815
21  High cholesterol among adults who have ever be...  Crude prevalence  78815
22  Housing insecurity in the past 12 months among...  Crude prevalence  60419
23         Independent living disability among adults  Crude prevalence  78815
24  Lack of reliable transportation in the past 12...  Crude prevalence  60419
25  Lack of social and emotional support among adults  Crude prevalence  60419
26                            Loneliness among adults  Crude prevalence  60419
27       Mammography use among women aged 50-74 years  Crude prevalence  83480
28                   Mobility disability among adults  Crude prevalence  78815
29     No leisure-time physical activity among adults  Crude prevalence  78815
30                               Obesity among adults  Crude prevalence  78815
31  Received food stamps in the past 12 months amo...  Crude prevalence  60419
32                  Self-care disability among adults  Crude prevalence  78815
33                  Short sleep duration among adults  Crude prevalence  83522
34                                Stroke among adults  Crude prevalence  78815
35  Taking medicine to control high blood pressure...  Crude prevalence  78815
36  Utility services shut-off threat in the past 1...  Crude prevalence  60419
37                     Vision disability among adults  Crude prevalence  78815
38  Visited dentist or dental clinic in the past y...  Crude prevalence  83522
39  Visits to doctor for routine checkup within th...  Crude prevalence  78815

Looks like all health measure use the Crude value for prevalence, therfore data looks at the raw, unadjusted heatlh reality across counties. 

**Note** 
This discovery introduces a limitation in our analysis. Our analysis is reflecting the acutal health burden of the population as it exist today, including the impact of age. For example, a county with an older population should have higher blood preassure rates. To get age adjusted data, we would need ot download the specific file form CDC PLACES portal. Future iterations may integrate 'Age-adjusted' data to control for age-related health disparities; however, for this analysis, we are measuring the raw reported prevalence of high blood pressure.

Crude data is great for measuring resource allocations for policymakers who needs to knwo who is affected regardless of the reason why. 
Age-adjusted data is better suited for health disparity/inequality research, as it allows for more accurate comparisons between populations with different age structures.

# Conclusion

Archive this dataset and use a version of the dataset that includes Age-adjisted Data.