# EDA Food Access Dataset  

# Introduction 

This dataset contains information about food access in various regions. It includes data on grocery stores, food deserts, and demographic information related to food accessibility. The goal of this exploratory data analysis (EDA) is to understand the distribution of food access across different areas and identify potential disparities.

# Importing Libraries

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

# Read The excel file

In [10]:
base_path = Path.cwd().parents[1]  # Get the parent directory of the current working directory

data_path = base_path / "data" / "raw"/ "FoodAccessResearchAtlasData2019.xlsx"

df = pd.read_excel(data_path, sheet_name="Food Access Research Atlas")

print(f"Data loaded successfully")

Data loaded successfully

# Preview the data

In [11]:
print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nRandom sample:")
display(df.sample(min(5, len(df)), random_state=42))

First 5 rows:

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.000000,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.341014,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.000000,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.000000,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.681219,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

Last 5 rows:

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
72526,56043000200,Wyoming,Washakie County,0,3326,1317,0,57.0,1.713770,0,...,593.0,3106.0,6.0,15.0,0.0,27.0,172.0,309.0,61.0,64.0
72527,56043000301,Wyoming,Washakie County,1,2665,1154,0,10.0,0.375235,0,...,399.0,2377.0,5.0,23.0,0.0,40.0,220.0,446.0,88.0,41.0
72528,56043000302,Wyoming,Washakie County,1,2542,1021,0,73.0,2.871755,0,...,516.0,2312.0,11.0,10.0,1.0,26.0,182.0,407.0,23.0,64.0
72529,56045951100,Wyoming,Weston County,0,3314,1322,0,252.0,7.604104,0,...,499.0,3179.0,15.0,10.0,1.0,47.0,62.0,91.0,47.0,34.0
72530,56045951300,Wyoming,Weston County,1,3894,1699,0,61.0,1.566513,0,...,650.0,3706.0,6.0,10.0,2.0,44.0,126.0,125.0,34.0,110.0

Random sample:

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
6366,6037536103,California,Los Angeles County,1,5516,1403,0,1.0,0.018129,0,...,412.0,2891.0,42.0,35.0,0.0,68.0,2480.0,5219.0,177.0,270.0
9405,6073009504,California,San Diego County,0,5914,1807,0,45.0,0.760906,0,...,394.0,4067.0,166.0,1268.0,13.0,15.0,385.0,438.0,16.0,11.0
40229,33011025500,New Hampshire,Hillsborough County,0,6235,2475,0,13.0,0.208500,0,...,684.0,6008.0,37.0,36.0,2.0,20.0,132.0,90.0,0.0,150.0
30900,24510240200,Maryland,Baltimore city,1,2564,1358,0,0.0,0.000000,0,...,246.0,2284.0,103.0,108.0,0.0,3.0,66.0,80.0,59.0,35.0
1696,4013104302,Arizona,Maricopa County,1,3209,1713,0,0.0,0.000000,1,...,285.0,2153.0,252.0,137.0,4.0,96.0,567.0,811.0,330.0,252.0

# Check dataset dimensions and columns

In [12]:
print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]:,}")

print("\nColumn names:")
print(df.columns.tolist())

Number of rows: 72,531
Number of columns: 147

Column names:
['CensusTract', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010', 'GroupQuartersFlag', 'NUMGQTRS', 'PCTGQTRS', 'LILATracts_1And10', 'LILATracts_halfAnd10', 'LILATracts_1And20', 'LILATracts_Vehicle', 'HUNVFlag', 'LowIncomeTracts', 'PovertyRate', 'MedianFamilyIncome', 'LA1and10', 'LAhalfand10', 'LA1and20', 'LATracts_half', 'LATracts1', 'LATracts10', 'LATracts20', 'LATractsVehicle_20', 'LAPOP1_10', 'LAPOP05_10', 'LAPOP1_20', 'LALOWI1_10', 'LALOWI05_10', 'LALOWI1_20', 'lapophalf', 'lapophalfshare', 'lalowihalf', 'lalowihalfshare', 'lakidshalf', 'lakidshalfshare', 'laseniorshalf', 'laseniorshalfshare', 'lawhitehalf', 'lawhitehalfshare', 'lablackhalf', 'lablackhalfshare', 'laasianhalf', 'laasianhalfshare', 'lanhopihalf', 'lanhopihalfshare', 'laaianhalf', 'laaianhalfshare', 'laomultirhalf', 'laomultirhalfshare', 'lahisphalf', 'lahisphalfshare', 'lahunvhalf', 'lahunvhalfshare', 'lasnaphalf', 'lasnaphalfshare', 'lapop1', 'lapop1share', 'lalowi1', 'lalowi1share', 'lakids1', 'lakids1share', 'laseniors1', 'laseniors1share', 'lawhite1', 'lawhite1share', 'lablack1', 'lablack1share', 'laasian1', 'laasian1share', 'lanhopi1', 'lanhopi1share', 'laaian1', 'laaian1share', 'laomultir1', 'laomultir1share', 'lahisp1', 'lahisp1share', 'lahunv1', 'lahunv1share', 'lasnap1', 'lasnap1share', 'lapop10', 'lapop10share', 'lalowi10', 'lalowi10share', 'lakids10', 'lakids10share', 'laseniors10', 'laseniors10share', 'lawhite10', 'lawhite10share', 'lablack10', 'lablack10share', 'laasian10', 'laasian10share', 'lanhopi10', 'lanhopi10share', 'laaian10', 'laaian10share', 'laomultir10', 'laomultir10share', 'lahisp10', 'lahisp10share', 'lahunv10', 'lahunv10share', 'lasnap10', 'lasnap10share', 'lapop20', 'lapop20share', 'lalowi20', 'lalowi20share', 'lakids20', 'lakids20share', 'laseniors20', 'laseniors20share', 'lawhite20', 'lawhite20share', 'lablack20', 'lablack20share', 'laasian20', 'laasian20share', 'lanhopi20', 'lanhopi20share', 'laaian20', 'laaian20share', 'laomultir20', 'laomultir20share', 'lahisp20', 'lahisp20share', 'lahunv20', 'lahunv20share', 'lasnap20', 'lasnap20share', 'TractLOWI', 'TractKids', 'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian', 'TractNHOPI', 'TractAIAN', 'TractOMultir', 'TractHispanic', 'TractHUNV', 'TractSNAP']

# Check data types and dataset information

In [13]:
print("Data types:")
display(df.dtypes.to_frame(name="data_type"))

print("\nDataset information:")
df.info()

Data types:

              data_type
CensusTract       int64
State            object
County           object
Urban             int64
Pop2010           int64
...                 ...
TractAIAN       float64
TractOMultir    float64
TractHispanic   float64
TractHUNV       float64
TractSNAP       float64

[147 rows x 1 columns]

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72531 entries, 0 to 72530
Columns: 147 entries, CensusTract to TractSNAP
dtypes: float64(126), int64(19), object(2)
memory usage: 81.3+ MB

# Check dup rows

In [14]:
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count:,}")
print(f"Duplicate percentage: {duplicate_count / len(df) * 100:.2f}%")

Number of duplicate rows: 0
Duplicate percentage: 0.00%

# Check missing values

In [22]:
df.isnull().sum()

CensusTract      0
State            0
County           0
Urban            0
Pop2010          0
                ..
TractAIAN        4
TractOMultir     4
TractHispanic    4
TractHUNV        4
TractSNAP        4
Length: 147, dtype: int64

In [15]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
})

missing_summary = (
    missing_summary
    .sort_values("missing_percent", ascending=False)
)

display(missing_summary)

                missing_count  missing_percent
lanhopi20               71025        97.923646
lalowi20                71025        97.923646
lanhopi20share          71025        97.923646
laaian20                71025        97.923646
laaian20share           71025        97.923646
...                       ...              ...
LATracts_half               0         0.000000
LATracts1                   0         0.000000
LATracts10                  0         0.000000
LATracts20                  0         0.000000
CensusTract                 0         0.000000

[147 rows x 2 columns]

## Show only columns with missingness

In [16]:
display(missing_summary[missing_summary["missing_count"] > 0])

                missing_count  missing_percent
lanhopi20               71025        97.923646
lalowi20                71025        97.923646
lanhopi20share          71025        97.923646
laaian20                71025        97.923646
laaian20share           71025        97.923646
...                       ...              ...
TractHispanic               4         0.005515
TractHUNV                   4         0.005515
TractWhite                  4         0.005515
TractSNAP                   4         0.005515
PovertyRate                 3         0.004136

[126 rows x 2 columns]

# Check Uniqe Values

In [18]:
unique_summary = pd.DataFrame({
    "unique_count": df.nunique(dropna=False),
    "unique_percent": df.nunique(dropna=False) / len(df) * 100
})

display(unique_summary.sort_values("unique_count"))

                    unique_count  unique_percent
LAhalfand10                    2        0.002757
LATractsVehicle_20             2        0.002757
LATracts20                     2        0.002757
LATracts10                     2        0.002757
LATracts1                      2        0.002757
...                          ...             ...
lawhitehalfshare           67507       93.073307
lapophalfshare             67563       93.150515
lapophalf                  67594       93.193255
PovertyRate                69948       96.438764
CensusTract                72531      100.000000

[147 rows x 2 columns]

# Generate Summary Statistics

In [21]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CensusTract,72531.0,2.782573e+10,1.581647e+10,1.001020e+09,1.212708e+10,2.712979e+10,4.103900e+10,5.604595e+10
Urban,72531.0,7.606265e-01,4.267040e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
Pop2010,72531.0,4.256739e+03,1.955988e+03,1.000000e+00,2.899000e+03,4.011000e+03,5.330500e+03,3.745200e+04
OHU2010,72531.0,1.609192e+03,7.256760e+02,0.000000e+00,1.108000e+03,1.525000e+03,2.021000e+03,1.604300e+04
GroupQuartersFlag,72531.0,7.114199e-03,8.404573e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
...,...,...,...,...,...,...,...,...
TractAIAN,72527.0,4.015232e+01,1.773787e+02,0.000000e+00,7.000000e+00,1.500000e+01,3.300000e+01,9.009000e+03
TractOMultir,72527.0,3.876646e+02,5.293497e+02,0.000000e+00,8.500000e+01,1.860000e+02,4.480000e+02,8.839000e+03
TractHispanic,72527.0,6.959793e+02,1.119473e+03,0.000000e+00,8.800000e+01,2.430000e+02,7.510000e+02,1.542000e+04
TractHUNV,72527.0,1.437097e+02,2.327389e+02,0.000000e+00,3.600000e+01,8.200000e+01,1.685000e+02,6.059000e+03
TractSNAP,72527.0,2.017532e+02,1.857601e+02,0.000000e+00,6.700000e+01,1.520000e+02,2.820000e+02,2.175000e+03

## Numeric columns

## Categorical Columns